# SPDX-FileCopyrightText: 2025 diggsweden/rest-api-profil-lint-processor
#
# SPDX-License-Identifier: EUPL-1.2

---
name: RAP-LP Pre-release

on:
  push:
    tags:
      - 'v*.*.*-alpha.*'
      - 'v*.*.*-beta.*'
      - 'v*.*.*-rc.*'

jobs:
  publish-package:
    uses: ./.github/workflows/publish-package.yaml
    permissions:
      contents: read
      packages: write

  publish-image:
    needs: publish-package
    uses: ./.github/workflows/publish-image.yaml
    permissions:
      contents: read
      packages: write

