# SPDX-FileCopyrightText: 2025 diggsweden/rest-api-profil-lint-processor
#
# SPDX-License-Identifier: EUPL-1.2

name: Publish package to GitHub Packages
on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Publish prerelease
        if: contains(github.ref_name, '-alpha.') || contains(github.ref_name, '-beta.') || contains(github.ref_name, '-rc.')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${GITHUB_REF_NAME}"
          if [[ "$TAG" =~ -alpha\. ]]; then DIST="alpha"; fi
          if [[ "$TAG" =~ -beta\. ]];  then DIST="beta";  fi
          if [[ "$TAG" =~ -rc\. ]];    then DIST="rc";    fi

          echo "Publishing prerelease with dist-tag: $DIST"
          npm publish --tag "$DIST"

      # Stable → publicera som latest
      - name: Publish stable
        if: ${{ !contains(github.ref_name, '-') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Publishing stable as latest"
          npm publish