# SPDX-FileCopyrightText: 2025 diggsweden/rest-api-profil-lint-processor
#
# SPDX-License-Identifier: EUPL-1.2

---
name: RAP-LP project Workflow

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*.*.*"

jobs:
  gate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      ok: ${{ steps.chk.outputs.ok }}
    steps:
      - id: chk
        shell: bash
        run: |
          if [[ "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "ok=true" >> "$GITHUB_OUTPUT"
          else
            echo "ok=false" >> "$GITHUB_OUTPUT"
          fi

  # Skapar en release tag som är stabil.
  publish-package:
    needs: gate
    if: needs.gate.outputs.ok == 'true'
    uses: ./.github/workflows/publish-package.yaml
    permissions:
      contents: read
      packages: write

  publish-image:
    needs: [gate, publish-package]
    if: needs.gate.outputs.ok == 'true'
    uses: ./.github/workflows/publish-image.yaml
    permissions:
      contents: read
      packages: write